export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/3.jpeg",
        username: "Safak Kocaoglu",
    },
    {
        id: 2,
        profilePicture: "assets/person/7.jpeg",
        username: "Janell Shrum",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Alex Durden",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpeg",
        username: "Dora Hawks",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Thomas Holden",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "Shirley Beauchamp",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Travis Bennett",
    },
    {
        id: 8,
        profilePicture: "assets/person/4.jpeg",
        username: "Kristen Thomas",
    },
    {
        id: 9,
        profilePicture: "assets/person/5.jpeg",
        username: "Gary Duty",
    },
    {
        id: 10,
        profilePicture: "assets/person/6.jpeg",
        username: "Safak Kocaoglu",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "https://i.pinimg.com/736x/83/dd/29/83dd2961a32eec253eb6af37344a12f2.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "https://i.pinimg.com/564x/03/30/e9/0330e9d45f9b49ab0a9f90960deef3b7.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "assets/post/3.jpeg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "https://i.pinimg.com/564x/8e/f5/b5/8ef5b52b8d49b6b35e898d6b6a85de9c.jpg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "https://i.pinimg.com/564x/05/4b/7f/054b7f58786d6db29c1ce11656b711ae.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "https://i.pinimg.com/564x/cc/48/05/cc4805345f95396e08a5a6947455df2a.jpg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "https://i.pinimg.com/564x/f2/d4/d7/f2d4d7b3015412a487f5fe56855f516a.jpg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "https://i.pinimg.com/564x/9c/59/4b/9c594be4975d86d3dee73c964b5cf34b.jpg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "https://i.pinimg.com/564x/65/cc/f8/65ccf86e994f922a5462d879f8b7560d.jpg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "https://i.pinimg.com/564x/fb/d0/fb/fbd0fb8f50a5b2748799c43d01f9e6e3.jpg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];
